# Site wide configuration

title:            Yunhui Li (李云辉)
locale:           en_US
url:


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Yunhui Li
  avatar: liyunhui.png
  bio: "Department of Automation Shanghai University: https://www.shu.edu.cn"
  email: liyunhui@shu.edu.cn
  disqus-shortname:
  twitter: #username
  facebook: #username
  google: 
    plus: 
    scholar: https://scholar.google.com/citations?user=DT6DSnoAAAAJ&hl=en
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: Yunhui-LI
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #canyilu
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
